module Sentiments
//https://www.theatlantic.com/technology/archive/2016/07/the-200-happiest-words-in-literature/490916/

let depressing_sentiment = ["Terrorist"; "suicide"; "terrorism"; "murder"; "death"; "cancer"; "killed"; "kill"; "died"; "torture"; "deaths"; "arrested"; "killing"; "die"; "terror"; "jail"; "kills"; "war"; "murdered"; "killings"; "fatal"; "tortured"; "abused"; "sickness"; "failed"; "cry"; "cruel"; "violence"; "sadness"; "diseases"; "abuse"; "wars"; "evil"; "earthquake"; "depressing"; "poison"; "fail"; "disaster"; "bomb"; "tumors"; "poverty"; "headache"; "depression"; "criminal"; "punishment"; "killers"; "illness"; "disease"; "dead"; "slavery"; "sick"; "motherfucker"; "rejection"; "injury"; "destroyed"; "crying"; "violent"; "tragedy"; "slaves"; "slave"; "prison"; "hates"; "failure"; "fails"; "bankruptcy"; "virus"; "suffer"; "robbery"; "rejected"; "racist"; "dies"; "worst"; "pain"; "funeral"; "dying"; "heartbreak"; "unhappy"; "unemployment"; "sorrow"; "painful"; "hurts"; "hated"; "crimes"; "corruption"; "pollution"; "homeless"; "drowned"; "agony"; "tsunami"; "robbed"; "hurt"; "divorced"; "depressed"; "loser"; "crime"; "cried"; "suffering"; "injured"]
let happy_sentiment = ["Laughter"; "happiness"; "love"; "happy"; "laughed"; "laugh"; "laughing"; "excellent"; "laughs"; "joy"; "successful"; "win"; "rainbow"; "smile"; "won"; "pleasure"; "smiled"; "rainbows"; "winning"; "celebration"; "enjoyed"; "healthy"; "music"; "celebrating"; "congratulations"; "weekend"; "celebrate"; "comedy"; "jokes"; "rich"; "victory"; "Christmas"; "free"; "friendship"; "fun"; "holidays"; "loved"; "loves"; "loving"; "beach"; "kissing"; "sunshine"; "delicious"; "friends"; "funny"; "outstanding"; "paradise"; "sweetest"; "vacation"; "butterflies"; "freedom"; "flower"; "great"; "sunlight"; "sweetheart"; "sweetness"; "award"; "chocolate"; "heaven"; "peace"; "splendid"; "success"; "enjoying"; "kissed"; "attraction"; "celebrated"; "hero"; "hugs"; "positive"; "sun"; "birthday"; "blessed"; "fantastic"; "winner"; "delight"; "beauty"; "butterfly"; "entertainment"; "funniest"; "honesty"; "sky"; "smiles"; "succeed"; "wonderful"; "glorious"; "kisses"; "promotion"; "family"; "gift"; "humor"; "romantic"; "cupcakes"; "festival"; "honour"; "relax"; "weekends"; "angel"; "bonus"; "brilliant"; "diamonds"; "holiday"; "lucky"; "mother"; "super"; "amazing"; "angels"; "enjoy"; "friend"; "friendly"; "mother's"; "profit"; "finest"; "champion"; "grandmother"; "kiss"; "kitten"; "miracle"; "mom"; "sweet"; "blessings"; "bright"; "cutest"; "entertaining"; "excited"; "excitement"; "joke"; "millionaire"; "prize"; "succeeded"; "successfully"; "winners"; "shines"; "awesome"; "genius"; "achievement"; "cake"; "cheers"; "exciting"; "goodness"; "hug"; "income"; "party"; "puppy"; "smiling"; "song"; "succeeding"; "tasty"; "victories"; "achieved"; "billion"; "cakes"; "easier"; "flowers"; "gifts"; "gold"; "merry"; "families"; "handsome"; "lovers"; "affection"; "candy"; "cute"; "diamond"; "earnings"; "interesting"; "peacefully"; "praise"; "relaxing"; "roses"; "Saturdays"; "faithful"; "heavens"; "cherish"; "comfort"; "congrats"; "cupcake"; "earn"; "extraordinary"; "glory"; "hilarious"; "moonlight"; "optimistic"; "peaceful"; "romance"; "feast"; "attractive"; "glad"; "grandma"; "internet"; "pleasant"; "profits"; "smart"]

let funny_sentiment = ["Hilarious" ;"Witty" ;"Amusing" ;"Comical" ;"Jovial" ;"Whimsical" ;"Zany";"Lighthearted" ;"Jocular" ;"Gleeful" ;"Eccentric" ;"Quirky" ;"Ridiculous" ;"Absurd" ;"Farcical" ;"Playful" ;"Hysterical" ;"Funny"]

let angry_sentiment = ["Furious";"Wrath";"Irritated";"Agitated";"Resentful";"Annoyed";"Incensed";"Livid";"Enraged";"Infuriated";"Exasperated";"Indignant";"Cross";"Vexed";"Irate";"Outraged";"Mad";"Hostile";"Bitter";"Fuming"]



